services:
  - type: web
    name: mlb-unicorn-engine
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unicorn-db
          property: connectionString

databases:
  - name: unicorn-db
    plan: free
